// MESSAGES
export const SEND_MESSAGE_ATTEMPT = 'SEND_MESSAGE_ATTEMPT';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAIL = 'SEND_MESSAGE_FAIL';
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';
// CLIENT
export const SET_LOGIN = 'SET_LOGIN';
export const SIGN_IN = 'SIGN_IN';
export const REQUEST_CLIENT_ID = 'REQUEST_CLIENT_ID';
export const SET_CLIENT_ID = 'SET_CLIENT_ID';
export const SET_TOKEN = 'SET_TOKEN';
export const SET_NICKNAME = 'SET_NICKNAME';
// TYPING
export const RECEIVE_TYPING = 'RECEIVE_TYPING';
export const STOP_TYPING_NOTIFICATION = 'STOP_TYPING_NOTIFICATION';
// CHATS
export const ADD_CHAT = 'ADD_CHAT';
export const DELETE_CHAT = 'DELETE_CHAT';
// POSTS
export const LOAD_POSTS = 'LOAD_POSTS';
export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS';
export const LOAD_POSTS_FAIL = 'LOAD_POSTS_FAIL';
// PUBLIC WALL
export const JOIN_WALL = 'JOIN_WALL';
export const JOIN_WALL_SUCCESS = 'JOIN_WALL_SUCCESS';
export const JOIN_WALL_FAIL = 'JOIN_WALL_FAIL';
export const LEAVE_WALL = 'LEAVE_WALL';
// WebSocket
export const WEBSOCKET_OPEN = 'WEBSOCKET_OPEN';
export const WEBSOCKET_CLOSED = 'WEBSOCKET_CLOSED';
